# Generated by Django 5.0.7 on 2024-07-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_delete_roleuser_auktsion_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleuser',
            name='role_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roleuser',
            name='role_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roleuser',
            name='role_views',
            field=models.BooleanField(default=False),
        ),
    ]
