# Generated by Django 5.0.6 on 2024-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Mayor', 'Mayor'), ('Captain', 'Captain'), ('Leytenant', 'Leytenant'), ('Serjant', 'Serjant'), ('Kursant', 'Kursant'), ('Saldat', 'Saldat')], default='Saldat', max_length=50, null=True),
        ),
    ]
