# Generated by Django 5.0.6 on 2024-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
