# Generated by Django 5.0.7 on 2024-07-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armiya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armiya.tasks')),
            ],
        ),
    ]
