# Generated by Django 5.0.7 on 2024-07-21 05:36

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Asked', 'Asked'), ('Expected', 'Expected'), ('Done', 'Done')], max_length=40)),
                ('ball', models.IntegerField()),
                ('definition', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Buyum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ekb_name', models.CharField(max_length=200)),
                ('ekb', models.IntegerField()),
                ('boshlangich_narx', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vabq', models.IntegerField()),
                ('sumq', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sh_rivojlanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Talablar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('mavzu', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('definition', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Asked', 'Asked'), ('Expected', 'Expected'), ('Done', 'Done')], max_length=200)),
                ('user', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TaskUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('qiymat', models.FloatField()),
                ('history', models.JSONField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Auktsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('kuni', models.DateField()),
                ('yutganlar', models.CharField(max_length=100)),
                ('buyumlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armiya.buyum')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryBalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Asked', 'Asked'), ('Expected', 'Expected'), ('Done', 'Done')], max_length=40)),
                ('ball', models.IntegerField()),
                ('definition', models.CharField(max_length=250)),
                ('balls_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armiya.balls')),
            ],
        ),
    ]
