# Generated by Django 5.0.7 on 2024-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='user_id',
            field=models.JSONField(default=list),
        ),
    ]
