# Generated by Django 5.0.6 on 2024-07-19 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskusers',
            old_name='score',
            new_name='ball',
        ),
        migrations.RenameField(
            model_name='taskusers',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='vab',
            old_name='value',
            new_name='qiymat',
        ),
        migrations.AlterUniqueTogether(
            name='taskusers',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='users',
        ),
        migrations.AddField(
            model_name='taskusers',
            name='users',
            field=models.ManyToManyField(related_name='armiya_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vab',
            name='history',
            field=models.JSONField(),
        ),
        migrations.RemoveField(
            model_name='taskusers',
            name='user',
        ),
    ]
