# Generated by Django 5.0.6 on 2024-07-19 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0003_rename_score_taskusers_ball_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tasks',
            name='users',
            field=models.ManyToManyField(related_name='army_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
