# Generated by Django 5.0.6 on 2024-07-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0004_tasks_scores_tasks_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='scores',
            field=models.JSONField(default=list),
        ),
    ]
