# Generated by Django 5.0.7 on 2024-07-25 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0004_alter_buyum_ekb_alter_buyum_ekb_name_buyumusers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyum',
            name='buyumusers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armiya.buyumusers'),
        ),
    ]
