# Generated by Django 5.0.6 on 2024-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0005_alter_tasks_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='scores',
            field=models.JSONField(default=dict),
        ),
    ]
