# Generated by Django 5.0.6 on 2024-07-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0006_alter_tasks_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='scores',
            new_name='ball',
        ),
    ]
