# Generated by Django 5.0.6 on 2024-07-19 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0006_alter_sh_rivojlanish_content_alter_talablar_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='users',
        ),
        migrations.AddField(
            model_name='tasks',
            name='users',
            field=models.ManyToManyField(related_name='armiya_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
