# Generated by Django 5.0.6 on 2024-07-19 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0007_remove_tasks_users_tasks_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='users',
        ),
        migrations.CreateModel(
            name='TaskUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(blank=True, null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armiya.tasks')),
                ('users', models.ManyToManyField(related_name='armiya_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
