# Generated by Django 5.0.6 on 2024-07-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0008_remove_tasks_ball_remove_tasks_users_taskusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskusers',
            old_name='task_id',
            new_name='task',
        ),
    ]
